### ISSUE TITLE
Question about Stby Value of FMGS

### ISSUE THREAD

**Issue by pizman** [spiliot/jeehellrmp#6]
Hi.
Sorry i not find youre Mail Adress for this Request....  This isn´t a issue... I Need youre help if posible.
At the moment i try to set a RMP via "Mobiflight"  ( a tool for Hardware FSX Comunication)

Here i got a big Problem....   It look like FMGS not supports it´s standby Frequency Offset.   This is NOT the FSUIPC Standard Offset  311A for Com1 for example.
I see this when i use the FMGS Config Key Bindings.... If i Swap or manipulate the Frequence in FMGS the StandBy is different to the Original and the decrease/increase not change the original.... BUT Change the fictive Value.

I Know it´s posible to make a improve system with using only FSUIPC and not comunicate with Jeehell... But its much complex as a direct Read. I need lots of Preconditions and different In/Output Settings then.
( Looks like youre Software here use standard Offsets too and ignore the FMGS Values! )

You are a advanced programmer i think....  Can you help me here ?   Do you know how i can Readout the StandBy of RMP1,2 and 3  AND the Status of LED on the RMPs ? 

My Plan:  I like to Readout the Values direct from FMGS  via a LUA Script that runs in FSUIPC and write this Values on Custom Offsets with this Lua script ! So i can use the Offsets for example with Mobiflight ! 

By the Way....  I Found out with SIOC Creator it´s posible to read Out this.....  And it would be posible to set this to an free offset (66c0 for example)  BUT  THEN  SIOC must run in backround all the time.
**I THINK**  If Sioc can read this out this must be possible with LUA too  (or not ??) 

Hope you can Help me !!
You can contact me via Mail   pizman@freenet.de   or i will oberve this Github Page too.  THKS !

**Comment by spiliot** [comment]
Hi. Unfortunately I've never used Mobiflight or SIOC so I really have no idea how they work.

FSUIPC is kind of ancient technology, most helpful in the early days but there are better ways to do things today that make it redundant at least for what I wanted to do. As you already seem to realize (or read), I don't talk to JH at the moment but directly to FS via simconnect.

Now if I understand your problem correctly, you're using FS's ACTIVE/STBY frequency offsets and JH key binding to TRANSFER/change the STB frequency. I _guess_ JH doesn't use FS's STBY frequencies but internal ones. This would be consistent with how the radios work in the real airbus where RMPx STB frequencies are not copied/shared to the other RMPs so it makes sense to do so.

So the answer to your question is to either:
- Use FS's frequencies and sacrifice the original RMPx functionality
- Discover if there are FSUIPC offsets for the JH provided STB frequencies that you can read from, or ask the programmer of JH to include them in a future version
- (if you have enough lower level coding skills or are willing to dive deep) ask and maybe get access to the hardware connect API, assuming the values are there (if they are simulated they must be or it would be easy to add them).

SIOC most probably uses a hardwareconnect dll to get access to all those values, if not then I guess the value is already available in FSUIPC and you need to search for it :)

In a future version of this tool I will add the complete RMP functionality but I will do so with a custom hardware connect dll which unfortunately will have to be closed sourced as the referenced API is not public. So even if I add this feature, it won't help you...

Hope I answered your questions. I will be closing this issue as it is irrelevant to the actual project but you can add more comments afterwards if you wish. I'll also drop you an email so you can contact me directly.

**Comment by pizman** [comment]
Hello.   

First Thank you verry much....    This question not about youre programm but you reply and help same Day....    It´s cool the Homecockpit Builders Family are realy nice guys !

To the Problem.

After thinking again and youre hints i understand the Problem is not only in the StandBy Value.....  In case that the Active Display on RMP 1,2,3 can show different Values, each  there must be a additional internal Variable, too.
When i check SIOC i see there are 6 internal Values ( like you think, too) . One for every Display each.   And the LED Status Values are supportet to... Intern !

After all i understand youre information about the Hardware Connect API, too. 
As you say .... Sioc Creator and FSUIPC  got a own DLL in FMGS Folder that managed this.

What i think about is another fact.... maby i describe wrong in first Posting.....
For example some AddOn Aircrafts not use FSUIPC Offsets...  But they need/MUST comunicate with the Simulator, too....   
I always thought this comunication can already be observed/manipulated via FSUIPC/Simconnect.      
In lots of cases the Data is in form of LVars. .... This can be read with LUA scripting, too. 

I request this in the Jeehell support Forum.....  Hope the guy reply that.

Hope you understnad right.....  I not need that jeehell give me this Data on specific Offsets   ( Maby his Range from Pete Dawson is realy small)
I only like to use a Lua Script in FSUIPC to read out this....  NOT via Sioc ... And not via a extra Hardware connect API.
I THINK it will be posible if the Jeehell Programmer simply add in FSUIPC Comunication dll  this Data parts  ( Not on a offset... maby as Lvars. )


Finaly  Thank you again for youre Informations and youre friendly support !

**Comment by spiliot** [comment]
Well when I'm available I'm always willing to help :)

I'm quite certain LVARS are not the way to go. These internal panel variables are not used in JH as it doesn't have an FS hosted panel. It looks like you will need to ask JH to export these variables in FSUIPC or use SIOC to indirectly access them as you already found out.

PS. Please note that despite receiving these notifications directly in your email your replies are publicly posted to the github issue. Not that something is wrong but in case you haven't noticed.

**Comment by pizman** [comment]
Oh Sorry....  I thought this was youre private Email Link.....
Now i got youre real Email, too. ( Just was in spam folder) 

If you want you can simply delete this Thread here....  theres no use for other People and for youre project at all.    I know now what i need  Thanks.
